[package]
name = "universal_coin"
version = "1.0.0"
authors = []

[addresses]
aptos_asset = "0x42"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
