[package]
name = "Examples"
version = "0.0.0"

[addresses]
aptos_framework = "0x1"
FACoin = "0x42"

[dependencies]
# AptosFramework = { local = "../../../framework/aptos-framework" }

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"
