[package]
name = "Examples"
version = "0.0.0"

[addresses]
aptos_framework = "0x1"
FACoin = "0x4c5179e8d2e4275478f731df0d56a2cb6368622e335b252c98a995d777ad6079"

[dependencies]
# AptosFramework = { local = "../../../framework/aptos-framework" }

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"
