[package]
name = "MultisigManagedCoin"
version = "0.0.0"

[addresses]
aptos_framework = "0x1"
example_addr = "0x42"

[dependencies]
# AptosFramework = { local = "../../../framework/aptos-framework" }
ManagedFungibleAsset = { local = ".. /managed_fungible_asset" }

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

# [dependencies.ManagedFungibleAsset]
# git = "https://github.com/aptos-labs/aptos-core.git"
# rev = "devnet"
# subdir = "aptos-move/managed_fungible_asset"
